# Generated by Django 5.0.6 on 2024-07-27 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("task_app", "0003_task_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="description",
        ),
    ]
